---
- name: TM Analytics Multi-OS Hardening
  hosts: all
  gather_facts: yes

  tasks:
    - name: "🐧 DETECTED: Ubuntu"
      include_tasks: ubuntu-custom/ubuntu_logic.yml
      when: ansible_distribution == "Ubuntu"

    - name: "🪟 DETECTED: Windows"
      include_tasks: window-custom/window_logic.yml
      when: ansible_os_family == "Windows"
