[ubuntu_servers]
52.237.80.6

[ubuntu_servers:vars]
ansible_user=ubuntu
ansible_connection=ssh
# Use 'sudo' for Ubuntu remediation
ansible_become=yes
ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
# Since we set up SSH keys earlier, we don't need a password here
